### NUMPY Library

 <!-- numpy was made in 2006 by Travis Oliphant. It is a powerful library
  for numerical computing in Python, providing support for large multi-dimensional 
  arrays and matrices, along with a collection of mathematical  functions to operate
   on these arrays efficiently.it was written in C -->

In [2]:
print("Hello  world")

Hello  world


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
# numpy is written in c which are compiled and superfast.this is the main reson numpy is upto 50x faster than python list
# The Birth of NumPy (2005): Travis Oliphant solved this problem by combining Numeric and Numarray into one single library, 
# which he named NumPy.


In [5]:
# in numpy arrays u hav only kept same datatype only rather than  list

In [6]:
# Basic array creation
import numpy as np
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
# list
a=[1,2,3,"hello",4]
a

[1, 2, 3, 'hello', 4]

In [8]:
# convert it to uni string
np.array(a)

array(['1', '2', '3', 'hello', '4'], dtype='<U21')

In [9]:
b=[1,2,3.5]
b

[1, 2, 3.5]

In [10]:
# convert it into float if one is in float then convert it all in float
np.array(b)

array([1. , 2. , 3.5])

In [11]:
# in list now
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
# now in array
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#Array Generation function

In [13]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [15]:
# one dimention array of xeros
import numpy as np
arr=np.zeros((6))
arr

array([0., 0., 0., 0., 0., 0.])

In [16]:
# two dimention array
arr=np.zeros((6,7))
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
arr=np.ones((6))
arr

array([1., 1., 1., 1., 1., 1.])

In [18]:
arr=np.ones((6,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
# linear space used for equally given space
# ek specific range mein barabar faasle (equally spaced)
# wale numbers generate karne ke liye use hota hai.
arr=np.linspace(1,50,5)
arr

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [20]:
# Random generation function


In [21]:
np.random.rand(5)

array([0.8999364 , 0.72417146, 0.76172299, 0.95999725, 0.28100252])

In [22]:
# standarization me -3 sy 3 tak values ati hy uske liye ye use hta
np.random.randn(5)

array([ 1.39662781, -0.05634685,  0.55224478, -1.92560426, -0.56247639])

In [23]:
# randint 6 tu  0 sy lekar 6 tak ek randdiom nmbr print krega
np.random.randint(6)

2

In [24]:
# agar ap zada nmbr chaty tu
np.random.randint(10,67,7)

array([33, 43, 23, 29, 31, 19, 35], dtype=int32)

In [25]:
# Array attributes
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.shape

(3, 3)

In [27]:
arr.size

9

In [28]:
arr.dtype

dtype('int64')

In [29]:
# array methods

In [30]:
arr=np.array([[1,2,3,4],[5,6,7,8],[3,5,3,5]])
arr.min()

np.int64(1)

In [31]:
arr.max()

np.int64(8)

In [32]:
arr.sum()

np.int64(52)

In [33]:
# column wise sum

np.sum(arr,axis=0)

array([ 9, 13, 13, 17])

In [34]:
# row wise sum
np.sum(arr,axis=1)

array([10, 26, 16])

In [35]:
# for mean value
arr.mean()

np.float64(4.333333333333333)

In [36]:
arr.std()

np.float64(1.9720265943665385)

In [37]:
# for maximum element index find
arr.argmax()

np.int64(7)

In [38]:
# for minium find index
arr.argmin()

np.int64(0)

In [39]:
# reshaping and resizing


In [40]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [41]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [42]:
# array resize
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [43]:
# array indexing

In [44]:
import numpy as np

In [45]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [46]:

# if u want one element one Index
arr[6]

np.int64(17)

In [47]:
# slicing access specific portion

In [48]:
arr[1:5]

array([12, 13, 14, 15])

In [49]:
arr[:5]

array([11, 12, 13, 14, 15])

In [50]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [51]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [52]:
# if u want to skip one value and print next one and so on
arr[3::2]

array([14, 16, 18, 20])

In [53]:
# numpy indexing and slicing of matrix

In [54]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [55]:
arr[0]

array([1, 2, 3, 4, 5])

In [56]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [57]:
arr[2]

array([11, 12, 13, 14, 15])

In [58]:
#above all  its mean the first element target rows 0,1,2,3

In [59]:
# now for specific row and column


In [60]:
# print one elemnt

arr[0,0]

np.int64(1)

In [61]:
arr[0,4]

np.int64(5)

In [62]:
arr[3,2]

np.int64(18)

In [63]:
arr[4,3]

np.int64(24)

In [64]:
# now if u want specific portion isy ye hta aga hm chaty kci specific proption me specific column
# sy lekar kci specific column tak print kerna h tu ye 
# logic hy 


In [65]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [66]:
arr[2:4,3:5]

array([[14, 15],
       [19, 20]])

In [67]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [68]:
# if u want specfic column

arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [69]:
# boolean indexing

In [70]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [71]:
# if u want even number etc

bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [72]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

## Array operations

In [73]:
import numpy as np

In [74]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a1


array([1, 2, 3, 4, 5])

In [75]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [76]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [77]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [78]:
a1-a2

array([-5, -5, -5, -5, -5])


## BROADCASTING

broadcasting ka matlb  hy ke ek array me 10 add kerdo phr kia krogy kyuke list me nahi hta na for loop lagaogy or pora
masla hta hy 

In [79]:
l=[1,2,3,4]
l
# l+10

[1, 2, 3, 4]

In [80]:
arr=np.array(l)
arr


array([1, 2, 3, 4])

In [81]:
arr+10

array([11, 12, 13, 14])

In [82]:
arr*7645

array([ 7645, 15290, 22935, 30580])

In [83]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [84]:
arr2=arr+10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [85]:
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

## Deep and Shallow copy

deep copy wo hti jab ap ek me broadcast kerty hu tu dosry me hota hy or shallow me nahi hta 

In [86]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [87]:
slice=a[0:5]
slice

array([1, 2, 3, 4, 5])

In [88]:
slice1=slice+10
slice1

array([11, 12, 13, 14, 15])

deep copy

In [89]:
b=a
b[0]=8987

In [90]:
b

array([8987,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

In [91]:
a

array([8987,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

In [92]:
b=a.copy() 
# isy copy banege or change nahi hga a me ok 
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [93]:
a

array([8987,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

## matrix operations

In [94]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [95]:
A

array([[1, 2],
       [3, 4]])

In [96]:
B

array([[5, 6],
       [7, 8]])

In [97]:
A*B
# ye multiply hojaega lekin ek array ka dosry array  ke sath index ke sath

# 1*5=5,2*6=12,3*7=21,4*8=32

array([[ 5, 12],
       [21, 32]])

In [98]:
A@B

# isme ye hta ke pehla array ka row  column ke sath multiply hta hy like this 
# 1*5+2*7=19, 1*6+2*8=22,3*5+4*7=43,3*6+4*8=50

array([[19, 22],
       [43, 50]])

In [99]:
# other command also
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [100]:
A

array([[1, 2],
       [3, 4]])

In [101]:
B

array([[5, 6],
       [7, 8]])

## Transpose--> row become column convert

In [102]:
A.T

array([[1, 3],
       [2, 4]])

## Advance ARRAY manipulation

In [103]:
A

array([[1, 2],
       [3, 4]])

In [104]:
B

array([[5, 6],
       [7, 8]])

stack mean u combine vectro arrays but we cnnot combine two arrays or matrix so u stack two vector 

 ###  stack array

In [105]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [106]:
np.vstack((a,b))
# v for vertically stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [107]:
np.hstack((a,b))
# h for horizantally stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [108]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### spliiting array

In [109]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [110]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [111]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [112]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [113]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [114]:
a=np.vsplit(c,4)

In [115]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


## excersise

## valid sudoku

In [116]:
import numpy as np

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [117]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [118]:
np.sum(s)

np.int64(405)

In [119]:
# for specific rows use 1 and columns use 0
np.sum(s,axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [120]:
np.sum(s,axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [121]:
b=np.sum(s,axis=1)
for i in b:
    if i!=45:
        print("ur sudoku is not valid")
        break
else:
    print("ur sudoku is valid for rows")

ur sudoku is valid for rows


In [122]:
b=np.sum(s,axis=0)
for i in b:
    if i!=45:
        print("ur sudo is not valid")
        break
else:
    print("ur sudoku is valid for column")

ur sudoku is valid for column


In [123]:
for i in range(0,9,3):
    for j in range(0,9,3):
        # print(s[i:i+3,j:j+3])
        n=s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


### Q2

In [124]:
import numpy as np

# columns=[age,math marks,science marks]
data=np.array([
    [18,85,78],  #student1
    [19,92,88],  #student2
    [17,76,95],   #student3
    [18,65,70],   #student4
    [20,90,85]     #student5
])

In [125]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [126]:
np.shape(data)
# or
data.shape

(5, 3)

### find the average age of students 

In [127]:
np.mean(data[:,0])

np.float64(18.4)

In [128]:
 # exctract math marks of students
data[:,1]

array([85, 92, 76, 65, 90])

In [129]:
# find the highest  science marks
np.max(data[:,2])

np.int64(95)

In [130]:
# get detail of the student who score more than 90 in math

data[data[:,1]>90]

array([[19, 92, 88]])

In [131]:
# increase math marks of all student
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [132]:
# find how many are younger than 19
len(data[data[:,0] <19])

3

In [133]:
# calculate the average marks in each subjects (columwise mean)
np.mean(data[:,1:],axis=0)


array([86.6, 83.2])

In [134]:
# get data of students whio scored at least 80 in both subject
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [135]:
# replace all science marks  less than 75 with zero
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [136]:
data[:,2] [data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])

In [137]:
# donu 75 sy kam wala o kro tu phr aisy hga 
data[:,1:3] [data[:,1:3]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18,  0,  0],
       [20, 95, 85]])